## BEGIN PARAMETER HELP ##

parameter_help_bool = true | false
parameter_help_positive_integer = >= 1
parameter_help_optional_positive_integer = >= 1, optional
parameter_help_float = float
parameter_help_range = range
parameter_help_fraction = fraction
parameter_help_file = file
parameter_help_h5ad = h5ad file
parameter_help_cellrank_methods = stability | top_n | eigengap | eigengap_coarse

parameter_help_hint_ORGANISM = mouse | human | escherichia-coli
parameter_help_description_ORGANISM = Organism used for gene resources.
parameter_help_hint_MEMORY = $(parameter_help_positive_integer)
parameter_help_description_MEMORY = Memory budget in GB.

parameter_help_hint_ALIGNMENT_TOOL = cellranger | star
parameter_help_description_ALIGNMENT_TOOL = Alignment and counting backend.
parameter_help_hint_STAR_CB_LEN = $(parameter_help_positive_integer)
parameter_help_description_STAR_CB_LEN = Cell-barcode length used by STAR.
parameter_help_hint_STAR_UMI_LEN = $(parameter_help_positive_integer)
parameter_help_description_STAR_UMI_LEN = UMI length used by STAR.
parameter_help_hint_STAR_WHITELIST = file, optional
parameter_help_description_STAR_WHITELIST = Barcode whitelist used by STAR.
parameter_help_hint_STAR_BARCODE_FILTER = auto | threshold | top
parameter_help_description_STAR_BARCODE_FILTER = Barcode selection method.
parameter_help_hint_STAR_MIN_UMI = $(parameter_help_optional_positive_integer)
parameter_help_description_STAR_MIN_UMI = Minimum UMI count for threshold mode.
parameter_help_hint_STAR_TOP_BARCODES = >= 1, optional
parameter_help_description_STAR_TOP_BARCODES = Number of top barcodes.

parameter_help_hint_GENE_DROPOUT = $(parameter_help_fraction)
parameter_help_description_GENE_DROPOUT = Maximum gene dropout fraction.
parameter_help_hint_GENE_EXPRESSION = $(parameter_help_range)
parameter_help_description_GENE_EXPRESSION = Range of expressing cells per gene.
parameter_help_hint_GENE_COUNTS = $(parameter_help_range)
parameter_help_description_GENE_COUNTS = Allowed range of total counts per gene.
parameter_help_hint_CELL_DROPOUT = $(parameter_help_fraction)
parameter_help_description_CELL_DROPOUT = Maximum cell dropout fraction.
parameter_help_hint_CELL_EXPRESSION = $(parameter_help_range)
parameter_help_description_CELL_EXPRESSION = Range of expressed genes per cell.
parameter_help_hint_CELL_READS = $(parameter_help_range)
parameter_help_description_CELL_READS = Allowed range of total reads per cell.
parameter_help_hint_MAD_DEVIATION = lower upper
parameter_help_description_MAD_DEVIATION = MAD factors around median log-reads.
parameter_help_hint_NORM_MAD = $(parameter_help_bool)
parameter_help_description_NORM_MAD = Use Gaussian-consistent MAD scaling.
parameter_help_hint_MT = $(parameter_help_fraction)
parameter_help_description_MT = Maximum mitochondrial count fraction.
parameter_help_hint_CC_CORRECTION = $(parameter_help_bool)
parameter_help_description_CC_CORRECTION = Regress out cell-cycle scores.

parameter_help_hint_ANALYSIS_HVG_FLAVOR = seurat | cell_ranger | seurat_v3
parameter_help_description_ANALYSIS_HVG_FLAVOR = Analysis HVG method.
parameter_help_hint_ANALYSIS_HVG_TOP = >= 1, optional
parameter_help_description_ANALYSIS_HVG_TOP = Number of top analysis HVGs.
parameter_help_hint_ANALYSIS_HVG_SPAN = $(parameter_help_float)
parameter_help_description_ANALYSIS_HVG_SPAN = Loess fraction for seurat_v3.
parameter_help_hint_ANALYSIS_HVG_BINS = $(parameter_help_positive_integer)
parameter_help_description_ANALYSIS_HVG_BINS = Mean-expression bins for analysis HVGs.
parameter_help_hint_INTEGRATION = bbknn | scanorama | ingest
parameter_help_description_INTEGRATION = Multi-condition integration method.
parameter_help_hint_DIM_PCA = $(parameter_help_positive_integer)
parameter_help_description_DIM_PCA = Number of PCA components.
parameter_help_hint_DIM_CLUSTERING = $(parameter_help_positive_integer)
parameter_help_description_DIM_CLUSTERING = PCA components used for clustering.
parameter_help_hint_DIM_EMBEDDING = $(parameter_help_positive_integer)
parameter_help_description_DIM_EMBEDDING = Number of embedding dimensions.
parameter_help_hint_PCA_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_PCA_ONLY_HVG = Restrict PCA projection to HVGs.
parameter_help_hint_NEIGHBORS = $(parameter_help_positive_integer)
parameter_help_description_NEIGHBORS = Number of nearest neighbors.
parameter_help_hint_METRIC = metric
parameter_help_description_METRIC = Distance metric for neighbors and t-SNE.
parameter_help_hint_RESOLUTION = $(parameter_help_float)
parameter_help_description_RESOLUTION = Leiden clustering resolution.
parameter_help_hint_MIN_DIST = $(parameter_help_float)
parameter_help_description_MIN_DIST = UMAP minimum distance.
parameter_help_hint_SPREAD = $(parameter_help_float)
parameter_help_description_SPREAD = UMAP spread.

parameter_help_hint_LOGFC = $(parameter_help_float)
parameter_help_description_LOGFC = Minimum absolute log2 fold-change.
parameter_help_hint_CORRECTION = benjamini-hochberg | bonferroni
parameter_help_description_CORRECTION = P-value correction method.
parameter_help_hint_ALPHA = $(parameter_help_float)
parameter_help_description_ALPHA = Adjusted p-value threshold.
parameter_help_hint_LABEL = labels
parameter_help_description_LABEL = Biological labels assigned to clusters.

parameter_help_hint_DIM_MOMENT = $(parameter_help_positive_integer)
parameter_help_description_DIM_MOMENT = PCA components for velocity moments.
parameter_help_hint_VELOCITY_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_VELOCITY_ONLY_HVG = Restrict RNA velocity to HVGs.
parameter_help_hint_SMM_MODE = deterministic | stochastic | dynamical
parameter_help_description_SMM_MODE = scVelo velocity model.
parameter_help_hint_BATCH_SIZE = $(parameter_help_positive_integer)
parameter_help_description_BATCH_SIZE = Cells processed per potency batch.
parameter_help_hint_SMOOTH_BATCH_SIZE = $(parameter_help_positive_integer)
parameter_help_description_SMOOTH_BATCH_SIZE = Cells sampled for smoothing.

parameter_help_hint_MACROSTATE_METHOD = knnbs | stream | cellrank | cotan
parameter_help_description_MACROSTATE_METHOD = Macrostate estimation method.
parameter_help_hint_MACROSTATE_SIZE = $(parameter_help_positive_integer)
parameter_help_description_MACROSTATE_SIZE = Target cells per macrostate.
parameter_help_hint_MACROSTATE_FILE = existing h5ad file
parameter_help_description_MACROSTATE_FILE = External macrostate entry point.
parameter_help_hint_COTAN_METHOD = classic | soft-merging | strong-merging
parameter_help_description_COTAN_METHOD = COTAN macrostate method.
parameter_help_hint_COTAN_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_COTAN_ONLY_HVG = Restrict COTAN to HVGs.
parameter_help_hint_MAX_ITER = $(parameter_help_positive_integer)
parameter_help_description_MAX_ITER = Maximum COTAN merging iterations.
parameter_help_hint_CELLRANK_METHOD = $(parameter_help_cellrank_methods)
parameter_help_description_CELLRANK_METHOD = Terminal-state selection method.
parameter_help_hint_STATES = $(parameter_help_positive_integer)
parameter_help_description_STATES = Number of CellRank macrostates.
parameter_help_hint_INITIAL_STATES = $(parameter_help_positive_integer)
parameter_help_description_INITIAL_STATES = Number of initial macrostates.
parameter_help_hint_TERMINAL_STATES = $(parameter_help_positive_integer)
parameter_help_description_TERMINAL_STATES = Terminal states for top_n.
parameter_help_hint_CELLRANK_STABILITY = $(parameter_help_float)
parameter_help_description_CELLRANK_STABILITY = Minimum stability.
parameter_help_hint_CELLRANK_ALPHA = $(parameter_help_float)
parameter_help_description_CELLRANK_ALPHA = Eigengap weighting parameter.
parameter_help_hint_CLUSTERING_METHOD = kmeans | ap | sc
parameter_help_description_CLUSTERING_METHOD = STREAM seed clustering method.
parameter_help_hint_CLUSTER_NUMBER = $(parameter_help_positive_integer)
parameter_help_description_CLUSTER_NUMBER = STREAM seed cluster number.
parameter_help_hint_ALPHA_EPG = $(parameter_help_float)
parameter_help_description_ALPHA_EPG = STREAM branch penalty.
parameter_help_hint_MU_EPG = $(parameter_help_float)
parameter_help_description_MU_EPG = STREAM harmonic embedding penalty.
parameter_help_hint_LAMBDA_EPG = $(parameter_help_float)
parameter_help_description_LAMBDA_EPG = STREAM edge-length penalty.
parameter_help_hint_EXTEND_EPG = $(parameter_help_bool)
parameter_help_description_EXTEND_EPG = Extend STREAM leaf nodes.
parameter_help_hint_EXTEND_MODE = QuantDists | QuantCentroid | WeigthedCentroid
parameter_help_description_EXTEND_MODE = STREAM extension mode.
parameter_help_hint_EXTEND_PARAMETER = $(parameter_help_float)
parameter_help_description_EXTEND_PARAMETER = STREAM extension parameter.
parameter_help_hint_PRUNE_EPG = $(parameter_help_bool)
parameter_help_description_PRUNE_EPG = Prune STREAM trivial branches.
parameter_help_hint_COLLAPSE_PARAMETER = $(parameter_help_bool)
parameter_help_description_COLLAPSE_PARAMETER = STREAM collapse parameter.
parameter_help_hint_KNNBS_EMBEDDING = obsm key
parameter_help_description_KNNBS_EMBEDDING = Embedding key for KNNBS distances.
parameter_help_hint_KNNBS_DIMENSION = dimensions, optional
parameter_help_description_KNNBS_DIMENSION = Embedding dimensions for distances.
parameter_help_hint_KNNBS_NEIGHBORS = $(parameter_help_positive_integer)
parameter_help_description_KNNBS_NEIGHBORS = KNN graph neighbor number.

parameter_help_hint_BIN_HVG_FLAVOR = seurat | cell_ranger | seurat_v3
parameter_help_description_BIN_HVG_FLAVOR = Shared HVG method for binarization.
parameter_help_hint_BIN_HVG_TOP = $(parameter_help_optional_positive_integer)
parameter_help_description_BIN_HVG_TOP = Number of top HVGs for binarization.
parameter_help_hint_BIN_HVG_SPAN = $(parameter_help_float)
parameter_help_description_BIN_HVG_SPAN = Loess cell fraction for seurat_v3.
parameter_help_hint_BIN_HVG_BINS = $(parameter_help_positive_integer)
parameter_help_description_BIN_HVG_BINS = Mean-expression bins for binarization HVG selection.
parameter_help_hint_BIN_SCBOOLSEQ_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_BIN_SCBOOLSEQ_ONLY_HVG = Restrict scBoolSeq to HVGs.
parameter_help_hint_UNIMODAL_QUANTILE = $(parameter_help_float)
parameter_help_description_UNIMODAL_QUANTILE = Threshold for unimodal genes.
parameter_help_hint_ZEROES_ARE_ZEROES = $(parameter_help_bool)
parameter_help_description_ZEROES_ARE_ZEROES = Set zero-inflated zeroes to 0.
parameter_help_hint_NANS_THRESHOLD = $(parameter_help_float)
parameter_help_description_NANS_THRESHOLD = Maximum undefined fraction.
parameter_help_hint_BIMODAL_THRESHOLD = $(parameter_help_float)
parameter_help_description_BIMODAL_THRESHOLD = Vote threshold for bimodal genes.
parameter_help_hint_ZEROINF_THRESHOLD = $(parameter_help_float)
parameter_help_description_ZEROINF_THRESHOLD = Zero-inflated vote threshold.
parameter_help_hint_UNIMODAL_THRESHOLD = $(parameter_help_float)
parameter_help_description_UNIMODAL_THRESHOLD = Unimodal vote threshold.
parameter_help_hint_BIN_DEA_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_BIN_DEA_ONLY_HVG = Restrict DEA binarization to HVGs.
parameter_help_hint_BIN_LOGFC = $(parameter_help_float)
parameter_help_description_BIN_LOGFC = Minimum absolute log2 fold-change.
parameter_help_hint_BIN_CORRECTION = benjamini-hochberg | bonferroni
parameter_help_description_BIN_CORRECTION = P-value correction method.
parameter_help_hint_BIN_ALPHA = $(parameter_help_float)
parameter_help_description_BIN_ALPHA = Adjusted p-value threshold.
parameter_help_hint_BIN_METHOD = scboolseq | dea | consensus
parameter_help_description_BIN_METHOD = Method used to binarize macrostates.
parameter_help_hint_BINARIZATION_FILE = existing binarization csv
parameter_help_description_BINARIZATION_FILE = External binarization file.

parameter_help_hint_SPEC_FILE = yaml file
parameter_help_description_SPEC_FILE = BoNesis model specification file.
parameter_help_hint_SPEC_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_SPEC_ONLY_HVG = Restrict model genes to bin HVGs.
parameter_help_hint_PRIOR_KNOWLEDGE = collectri | dorothea | file
parameter_help_description_PRIOR_KNOWLEDGE = Prior regulatory resource.
parameter_help_hint_DOROTHEA_API = current | legacy
parameter_help_description_DOROTHEA_API = DoRothEA API source.
parameter_help_hint_DOROTHEA_LEVELS = A | B | C | D
parameter_help_description_DOROTHEA_LEVELS = DoRothEA confidence levels.
parameter_help_hint_MAX_CLAUSE = $(parameter_help_positive_integer)
parameter_help_description_MAX_CLAUSE = Maximum literals per Boolean formula.
parameter_help_hint_CANONIC_FILTER = $(parameter_help_bool)
parameter_help_description_CANONIC_FILTER = Use canonical functions.
parameter_help_hint_CANONIC_INFER = $(parameter_help_bool)
parameter_help_description_CANONIC_INFER = Use canonical functions.
parameter_help_hint_MIN_SELF_LOOP_CONSTS = $(parameter_help_bool)
parameter_help_description_MIN_SELF_LOOP_CONSTS = Minimize one-node feedbacks.
parameter_help_hint_MIN_SELF_LOOP_INFER = $(parameter_help_bool)
parameter_help_description_MIN_SELF_LOOP_INFER = Minimize one-node feedbacks.
parameter_help_hint_CONFIG_FORMATS = csv | cfg | json
parameter_help_description_CONFIG_FORMATS = Configuration export formats.
parameter_help_hint_GRAPH_FORMATS = dot | neato | circo | fdp | sfdp
parameter_help_description_GRAPH_FORMATS = Graphviz layouts to export.
parameter_help_hint_INFER_LIMIT = >= 0, optional
parameter_help_description_INFER_LIMIT = Maximum number of inferred BNs.

parameter_help_hint_CLINGO_CONFIG_SOFT = clingo config or file
parameter_help_hint_CLINGO_CONFIG_CONSTS = clingo config or file
parameter_help_hint_CLINGO_CONFIG_RELAXED = clingo config or file
parameter_help_hint_CLINGO_CONFIG_SEED = clingo config or file
parameter_help_hint_CLINGO_CONFIG_LOCK = clingo config or file
parameter_help_description_CLINGO_CONFIG_SOFT = Clingo config for soft.
parameter_help_description_CLINGO_CONFIG_CONSTS = Clingo config for consts.
parameter_help_description_CLINGO_CONFIG_RELAXED = Clingo config for relaxed.
parameter_help_description_CLINGO_CONFIG_SEED = Clingo config for seed.
parameter_help_description_CLINGO_CONFIG_LOCK = Clingo config for lock.

parameter_help_hint_CLINGO_OPT_MODE_SOFT = opt | optN | ignore
parameter_help_hint_CLINGO_OPT_MODE_CONSTS = opt | optN | ignore
parameter_help_hint_CLINGO_OPT_MODE_RELAXED = opt | optN | ignore
parameter_help_hint_CLINGO_OPT_MODE_SEED = opt | optN | ignore
parameter_help_hint_CLINGO_OPT_MODE_LOCK = opt | optN | ignore
parameter_help_hint_CLINGO_OPT_MODE_MIN = opt | optN | ignore
parameter_help_description_CLINGO_OPT_MODE_SOFT = Optimization mode for soft.
parameter_help_description_CLINGO_OPT_MODE_CONSTS = Opt mode for consts.
parameter_help_description_CLINGO_OPT_MODE_RELAXED = Opt mode for relaxed.
parameter_help_description_CLINGO_OPT_MODE_SEED = Optimization mode for seed.
parameter_help_description_CLINGO_OPT_MODE_LOCK = Optimization mode for lock.
parameter_help_description_CLINGO_OPT_MODE_MIN = Optimization mode for bn-min.

parameter_help_hint_CLINGO_OPT_STRATEGY_SOFT = bb,* | usc,*
parameter_help_hint_CLINGO_OPT_STRATEGY_CONSTS = bb,* | usc,*
parameter_help_hint_CLINGO_OPT_STRATEGY_RELAXED = bb,* | usc,*
parameter_help_hint_CLINGO_OPT_STRATEGY_SEED = bb,* | usc,*
parameter_help_hint_CLINGO_OPT_STRATEGY_LOCK = bb,* | usc,*
parameter_help_description_CLINGO_OPT_STRATEGY_SOFT = Opt strategy for soft.
parameter_help_description_CLINGO_OPT_STRATEGY_CONSTS = Opt strategy for consts.
parameter_help_description_CLINGO_OPT_STRATEGY_RELAXED = Opt strategy.
parameter_help_description_CLINGO_OPT_STRATEGY_SEED = Opt strategy for seed.
parameter_help_description_CLINGO_OPT_STRATEGY_LOCK = Opt strategy for lock.

parameter_help_hint_JOBS_SOFT = $(parameter_help_positive_integer)
parameter_help_hint_JOBS_CONSTS = $(parameter_help_positive_integer)
parameter_help_hint_JOBS_RELAXED = $(parameter_help_positive_integer)
parameter_help_hint_JOBS_SEED = $(parameter_help_positive_integer)
parameter_help_hint_JOBS_LOCK = $(parameter_help_positive_integer)
parameter_help_description_JOBS_SOFT = Solver jobs for max-nodes-soft.
parameter_help_description_JOBS_CONSTS = Solver jobs for max-consts-soft.
parameter_help_description_JOBS_RELAXED = Solver jobs for max-nodes-relaxed.
parameter_help_description_JOBS_SEED = Solver jobs for max-nodes-seed.
parameter_help_description_JOBS_LOCK = Solver jobs for max-nodes-lock.

parameter_help_hint_TIMEOUT_SOFT = timeout
parameter_help_hint_TIMEOUT_CONSTS = timeout
parameter_help_hint_TIMEOUT_RELAXED = timeout
parameter_help_hint_TIMEOUT_SEED = timeout
parameter_help_hint_TIMEOUT_LOCK = timeout
parameter_help_description_TIMEOUT_SOFT = GNU timeout for max-nodes-soft.
parameter_help_description_TIMEOUT_CONSTS = GNU timeout for max-consts-soft.
parameter_help_description_TIMEOUT_RELAXED = GNU timeout for max-nodes-relaxed.
parameter_help_description_TIMEOUT_SEED = GNU timeout for max-nodes-seed.
parameter_help_description_TIMEOUT_LOCK = GNU timeout for max-nodes-lock.

## END PARAMETER HELP ##
