## MANDATORY PARAMETERS ##

RESULTS = nestorowa
CONDITIONS = unique

## USER-UPDATED PARAMETERS ##

JOBS = 16
SEED = 2
TIMEOUT = 100h
GRN_DATABASE = dorothea
MODEL_HVG_METHOD = cell_ranger
USE_REP = X_se
YAML_MODEL = user/nestorowa/spec.yml
MACROSTATE_METHOD = stream
MACROSTATE_SIZE = 25
BIN_METHOD = merge

## STREAM PARAMETERS ##

CLUSTER_NUMBER = 20
ALPHA_EPG = 0.01
MU_EPG = 0.02
LAMBDA_EPG = 0.01
EXTEND_EPG = true
EXTEND_PARAMETER = 0.8
PRUNE_EPG = false

## USER-DEFINED PARAMETERS ##

MAX_CLAUSE = 8
CLINGO_OPT_MODE = optN
CLINGO_OPT_STRATEGY = bb,inc
FILTER_MIN_FEEDBACKS = false
INFER_MIN_FEEDBACKS = false
INFER_LIMIT = 100