## BEGIN PARAMETER HELP ##

parameter_help_bool = true | false
parameter_help_positive_integer = >= 1
parameter_help_optional_positive_integer = >= 1, optional
parameter_help_float = float
parameter_help_range = range
parameter_help_fraction = fraction
parameter_help_file = file
parameter_help_h5ad = h5ad file
parameter_help_cellrank_methods = stability | top_n | eigengap | eigengap_coarse
parameter_help_clingo_configs = clingo config
parameter_help_clingo_config_note = clingo config: auto, frumpy, jumpy, tweety, handy, crafty, trendy, many.
parameter_help_clingo_mode_note = opt gives fast anytime solutions.
parameter_help_clingo_mode_note2 = optN targets certified optima.
parameter_help_clingo_mode_note3 = ignore disables optimization objectives and returns a satisfiable model.
parameter_help_clingo_strategy_note = bb,* uses branch-and-bound.
parameter_help_clingo_strategy_note2 = usc,* uses unsat-core optimization.
parameter_help_timeout_note = Use NUMBER[s|m|h|d]; empty value means no timeout.

parameter_help_hint_ORGANISM = mouse | human | escherichia-coli
parameter_help_description_ORGANISM = Organism used for gene resources.
parameter_help_hint_REPRESENTATION = X_umap | X_tsne | X_se
parameter_help_description_REPRESENTATION = Embedding computed by clustering.
parameter_help_note_REPRESENTATION = X_umap: UMAP embedding.
parameter_help_note2_REPRESENTATION = X_tsne: t-SNE embedding.
parameter_help_note3_REPRESENTATION = X_se: spectral embedding.
parameter_help_hint_MEMORY = memory size
parameter_help_description_MEMORY = Memory budget. Integers are interpreted as GB.
parameter_help_note_MEMORY = Cell Ranger receives an integer GB value.
parameter_help_note2_MEMORY = Velocyto receives MB per Samtools thread, computed from memory/jobs.
parameter_help_note3_MEMORY = Domain continuation uses memory as a soft candidate-portfolio limit.
parameter_help_hint_JOBS = $(parameter_help_positive_integer)
parameter_help_description_JOBS = Maximum number of parallel workflow jobs.
parameter_help_note_JOBS = Domain continuation evaluates up to jobs candidate domains simultaneously.
parameter_help_hint_BACKEND = conda | mamba | micromamba | docker
parameter_help_description_BACKEND = Backend used to execute module commands.
parameter_help_hint_SCBOLT_IMAGE = container image
parameter_help_description_SCBOLT_IMAGE = Docker image containing scBOLT micromamba environments.
parameter_help_hint_SCBOLT_CONTAINER_ENGINE = docker-compatible command
parameter_help_description_SCBOLT_CONTAINER_ENGINE = Container engine used when backend=docker.
parameter_help_hint_SCBOLT_CONTAINER_ARGS = arguments, optional
parameter_help_description_SCBOLT_CONTAINER_ARGS = Extra arguments passed to docker run.
parameter_help_hint_SCBOLT_CONTAINER_MOUNTS = paths, optional
parameter_help_description_SCBOLT_CONTAINER_MOUNTS = Extra host paths mounted at the same absolute path.
$(foreach condition,$(conditions),\
	$(eval parameter_help_hint_$(call gsm_var,$(condition)) = GSM accession)\
	$(eval parameter_help_description_$(call gsm_var,$(condition)) = GEO sample containing the count matrix.))

parameter_help_hint_ALIGNMENT_TOOL = cellranger | star
parameter_help_description_ALIGNMENT_TOOL = Alignment and counting backend.
parameter_help_hint_STAR_CB_LEN = $(parameter_help_positive_integer)
parameter_help_description_STAR_CB_LEN = Cell-barcode length used by STAR.
parameter_help_hint_STAR_UMI_LEN = $(parameter_help_positive_integer)
parameter_help_description_STAR_UMI_LEN = UMI length used by STAR.
parameter_help_hint_STAR_WHITELIST = file, optional
parameter_help_description_STAR_WHITELIST = Barcode whitelist used by STAR.
parameter_help_hint_STAR_BARCODE_FILTER = auto | threshold | top
parameter_help_description_STAR_BARCODE_FILTER = Barcode selection method.
parameter_help_hint_STAR_MIN_UMI = $(parameter_help_optional_positive_integer)
parameter_help_description_STAR_MIN_UMI = Minimum UMI count for threshold mode.
parameter_help_hint_STAR_TOP_BARCODES = >= 1, optional
parameter_help_description_STAR_TOP_BARCODES = Number of top barcodes.

parameter_help_hint_GENE_DROPOUT = $(parameter_help_fraction)
parameter_help_description_GENE_DROPOUT = Maximum gene dropout fraction.
parameter_help_hint_GENE_EXPRESSION = $(parameter_help_range)
parameter_help_description_GENE_EXPRESSION = Range of expressing cells per gene.
parameter_help_hint_GENE_COUNTS = $(parameter_help_range)
parameter_help_description_GENE_COUNTS = Allowed range of total counts per gene.
parameter_help_hint_CELL_DROPOUT = $(parameter_help_fraction)
parameter_help_description_CELL_DROPOUT = Maximum cell dropout fraction.
parameter_help_hint_CELL_EXPRESSION = $(parameter_help_range)
parameter_help_description_CELL_EXPRESSION = Range of expressed genes per cell.
parameter_help_hint_CELL_READS = $(parameter_help_range)
parameter_help_description_CELL_READS = Allowed range of total reads per cell.
parameter_help_hint_MAD_DEVIATION = lower upper
parameter_help_description_MAD_DEVIATION = MAD factors around median log-reads.
parameter_help_hint_CONSISTENT_MAD = $(parameter_help_bool)
parameter_help_description_CONSISTENT_MAD = Use Gaussian-consistent MAD scaling.
parameter_help_hint_MT = $(parameter_help_fraction)
parameter_help_description_MT = Maximum mitochondrial count fraction.
parameter_help_hint_CC_CORRECTION = $(parameter_help_bool)
parameter_help_description_CC_CORRECTION = Regress out cell-cycle scores.

parameter_help_hint_OMICS_HVG_METHOD = loess | binning
parameter_help_description_OMICS_HVG_METHOD = Shared HVG method for single-cell omics analysis.
parameter_help_note_OMICS_HVG_METHOD = The loess method reproduces the Seurat v3
parameter_help_note2_OMICS_HVG_METHOD = LOESS-regularized mean-variance strategy.
parameter_help_note3_OMICS_HVG_METHOD = The binning method reproduces the Cell Ranger
parameter_help_note4_OMICS_HVG_METHOD = mean-binned normalized dispersion strategy.
parameter_help_hint_OMICS_HVG_TOP = >= 1, optional
parameter_help_description_OMICS_HVG_TOP = Number of top HVGs for omics analysis.
parameter_help_hint_OMICS_HVG_SPAN = $(parameter_help_float)
parameter_help_description_OMICS_HVG_SPAN = Loess smoothing fraction.
parameter_help_hint_OMICS_HVG_BINS = $(parameter_help_positive_integer)
parameter_help_description_OMICS_HVG_BINS = Mean-expression bins for omics HVG selection.
parameter_help_hint_INTEGRATION = bbknn | scanorama | ingest
parameter_help_description_INTEGRATION = Multi-condition integration method.
parameter_help_hint_DIM_PCA = $(parameter_help_positive_integer)
parameter_help_description_DIM_PCA = Number of PCA components.
parameter_help_hint_DIM_EMBEDDING = $(parameter_help_positive_integer)
parameter_help_description_DIM_EMBEDDING = Number of embedding dimensions.
parameter_help_hint_CENTERED_PCA = $(parameter_help_bool)
parameter_help_description_CENTERED_PCA = Center variables before PCA.
parameter_help_hint_PCA_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_PCA_ONLY_HVG = Restrict PCA projection to HVGs.
parameter_help_hint_NEIGHBORS = $(parameter_help_positive_integer)
parameter_help_description_NEIGHBORS = Number of nearest neighbors.
parameter_help_hint_METRIC = distance metric
parameter_help_description_METRIC = Distance metric for neighbors and t-SNE.
parameter_help_hint_RESOLUTION = $(parameter_help_float)
parameter_help_description_RESOLUTION = Leiden clustering resolution.
parameter_help_hint_MIN_DIST = $(parameter_help_float)
parameter_help_description_MIN_DIST = UMAP minimum distance.
parameter_help_hint_SPREAD = $(parameter_help_float)
parameter_help_description_SPREAD = UMAP spread.
parameter_help_hint_EMBEDDING_N_ITER = $(parameter_help_positive_integer)
parameter_help_description_EMBEDDING_N_ITER = Embedding optimization iterations.

parameter_help_hint_DEA_METHOD = wilcoxon | welch | welch_overestimate
parameter_help_description_DEA_METHOD = Statistical test for marker differential expression.
parameter_help_hint_LOGFC = $(parameter_help_float)
parameter_help_description_LOGFC = Minimum absolute log2 fold-change.
parameter_help_hint_CORRECTION = benjamini-hochberg | bonferroni
parameter_help_description_CORRECTION = P-value correction method.
parameter_help_hint_ALPHA = $(parameter_help_float)
parameter_help_description_ALPHA = Adjusted p-value threshold.
parameter_help_hint_LABEL = ordered label list
parameter_help_description_LABEL = Biological labels assigned to clusters in cluster order.

parameter_help_hint_DIM_MOMENT = $(parameter_help_positive_integer)
parameter_help_description_DIM_MOMENT = PCA components for velocity moments.
parameter_help_hint_VELOCITY_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_VELOCITY_ONLY_HVG = Restrict RNA velocity to HVGs.
parameter_help_hint_SMM_MODE = deterministic | stochastic | dynamical
parameter_help_description_SMM_MODE = scVelo mode used to estimate RNA velocity.
parameter_help_hint_BATCH_SIZE = $(parameter_help_positive_integer)
parameter_help_description_BATCH_SIZE = Cells processed per potency batch.
parameter_help_hint_SMOOTH_BATCH_SIZE = $(parameter_help_positive_integer)
parameter_help_description_SMOOTH_BATCH_SIZE = Cells sampled for smoothing.

parameter_help_hint_MACROSTATE_METHOD = knnsc | stream | cellrank | cotan
parameter_help_description_MACROSTATE_METHOD = Macrostate estimation method.
parameter_help_hint_MACROSTATE_SIZE = $(parameter_help_positive_integer)
parameter_help_description_MACROSTATE_SIZE = Target cells per macrostate.
parameter_help_hint_COUNT_FILES = h5ad files
parameter_help_description_COUNT_FILES = External AnnData files containing layer 'counts', ordered like conditions.
parameter_help_hint_MACROSTATE_FILES = h5ad file(s)
parameter_help_description_MACROSTATE_FILES = External macrostate AnnData files using named expression layers.
parameter_help_hint_COUNT_FILE = h5ad file
parameter_help_description_COUNT_FILE = External AnnData file containing layer 'counts'.
parameter_help_hint_MACROSTATE_FILE = h5ad file
parameter_help_description_MACROSTATE_FILE = External macrostate AnnData file using named expression layers.
$(foreach condition,$(conditions),\
	$(eval parameter_help_hint_$(call count_file_var,$(condition)) = h5ad file)\
	$(eval parameter_help_description_$(call count_file_var,$(condition)) = External AnnData file containing layer 'counts'.)\
	$(eval parameter_help_hint_$(call macrostate_file_var,$(condition)) = h5ad file)\
	$(eval parameter_help_description_$(call macrostate_file_var,$(condition)) = External macrostate AnnData file using named expression layers.))
parameter_help_hint_COTAN_METHOD = classic | soft-merging | strong-merging
parameter_help_description_COTAN_METHOD = COTAN macrostate method.
parameter_help_hint_COTAN_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_COTAN_ONLY_HVG = Restrict COTAN to HVGs.
parameter_help_hint_MAX_ITER = $(parameter_help_positive_integer)
parameter_help_description_MAX_ITER = Maximum COTAN merging iterations.
parameter_help_hint_CELLRANK_METHOD = $(parameter_help_cellrank_methods)
parameter_help_description_CELLRANK_METHOD = Terminal-state selection method.
parameter_help_hint_STATES = $(parameter_help_positive_integer)
parameter_help_description_STATES = Number of CellRank macrostates.
parameter_help_hint_INITIAL_STATES = $(parameter_help_positive_integer)
parameter_help_description_INITIAL_STATES = Number of initial macrostates.
parameter_help_hint_TERMINAL_STATES = $(parameter_help_positive_integer)
parameter_help_description_TERMINAL_STATES = Terminal states for top_n.
parameter_help_hint_CELLRANK_STABILITY = $(parameter_help_float)
parameter_help_description_CELLRANK_STABILITY = Minimum stability.
parameter_help_hint_CELLRANK_ALPHA = $(parameter_help_float)
parameter_help_description_CELLRANK_ALPHA = Eigengap weighting parameter.
parameter_help_hint_CLUSTERING_METHOD = kmeans | ap | sc
parameter_help_description_CLUSTERING_METHOD = STREAM seed clustering method.
parameter_help_hint_CLUSTER_NUMBER = $(parameter_help_positive_integer)
parameter_help_description_CLUSTER_NUMBER = STREAM seed cluster number.
parameter_help_hint_ALPHA_EPG = $(parameter_help_float)
parameter_help_description_ALPHA_EPG = STREAM branch penalty.
parameter_help_hint_MU_EPG = $(parameter_help_float)
parameter_help_description_MU_EPG = STREAM harmonic embedding penalty.
parameter_help_hint_LAMBDA_EPG = $(parameter_help_float)
parameter_help_description_LAMBDA_EPG = STREAM edge-length penalty.
parameter_help_hint_EXTEND_EPG = $(parameter_help_bool)
parameter_help_description_EXTEND_EPG = Extend STREAM leaf nodes.
parameter_help_hint_EXTEND_MODE = QuantDists | QuantCentroid | WeigthedCentroid
parameter_help_description_EXTEND_MODE = STREAM extension mode.
parameter_help_hint_EXTEND_PARAMETER = $(parameter_help_float)
parameter_help_description_EXTEND_PARAMETER = STREAM extension parameter.
parameter_help_hint_PRUNE_EPG = $(parameter_help_bool)
parameter_help_description_PRUNE_EPG = Prune STREAM trivial branches.
parameter_help_hint_COLLAPSE_PARAMETER = $(parameter_help_bool)
parameter_help_description_COLLAPSE_PARAMETER = STREAM collapse parameter.
parameter_help_hint_KNNSC_EMBEDDING = obsm key
parameter_help_description_KNNSC_EMBEDDING = Embedding key for KNNSC distances.
parameter_help_hint_KNNSC_DIMENSION = dimensions, optional
parameter_help_description_KNNSC_DIMENSION = Embedding dimensions for distances.
parameter_help_hint_KNNSC_NEIGHBORS = $(parameter_help_positive_integer)
parameter_help_description_KNNSC_NEIGHBORS = KNN graph neighbor number.
parameter_help_hint_KNNSC_MIN_CLUSTER_SIZE = >= 0
parameter_help_description_KNNSC_MIN_CLUSTER_SIZE = Minimum label size for KNNSC candidates.
$(foreach condition,$(conditions),\
	$(eval parameter_help_hint_$(call knnsc_centrality_var,$(condition)) = label list, optional)\
	$(eval parameter_help_description_$(call knnsc_centrality_var,$(condition)) = Labels selected near their own barycenter.)\
	$(eval parameter_help_hint_$(call knnsc_periphery_var,$(condition)) = label list, optional)\
	$(eval parameter_help_description_$(call knnsc_periphery_var,$(condition)) = Labels selected far from other barycenters.))

parameter_help_hint_BIN_HVG_METHOD = loess | binning
parameter_help_description_BIN_HVG_METHOD = Shared HVG method for binarization.
parameter_help_note_BIN_HVG_METHOD = The loess method reproduces the Seurat v3
parameter_help_note2_BIN_HVG_METHOD = LOESS-regularized mean-variance strategy.
parameter_help_note3_BIN_HVG_METHOD = The binning method reproduces the Cell Ranger
parameter_help_note4_BIN_HVG_METHOD = mean-binned normalized dispersion strategy.
parameter_help_hint_BIN_HVG_TOP = $(parameter_help_optional_positive_integer)
parameter_help_description_BIN_HVG_TOP = Number of top HVGs for binarization.
parameter_help_hint_BIN_HVG_SPAN = $(parameter_help_float)
parameter_help_description_BIN_HVG_SPAN = Loess smoothing fraction.
parameter_help_hint_BIN_HVG_BINS = $(parameter_help_positive_integer)
parameter_help_description_BIN_HVG_BINS = Mean-expression bins for binarization HVG selection.
parameter_help_hint_BIN_INCLUDE_NODES = node list, optional
parameter_help_description_BIN_INCLUDE_NODES = Additional nodes retained when binarization uses only HVGs.
parameter_help_hint_BIN_SCBOOLSEQ_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_BIN_SCBOOLSEQ_ONLY_HVG = Restrict scBoolSeq to HVGs.
parameter_help_hint_SCBOOLSEQ_OPENBLAS_THREADS = auto | >= 1
parameter_help_description_SCBOOLSEQ_OPENBLAS_THREADS = OpenBLAS threads for scBoolSeq.
parameter_help_hint_SCBOOLSEQ_OMP_THREADS = auto | >= 1
parameter_help_description_SCBOOLSEQ_OMP_THREADS = OpenMP threads for scBoolSeq.
parameter_help_hint_UNIMODAL_QUANTILE = $(parameter_help_float)
parameter_help_description_UNIMODAL_QUANTILE = Threshold for unimodal genes.
parameter_help_hint_ZEROES_ARE_ZEROES = $(parameter_help_bool)
parameter_help_description_ZEROES_ARE_ZEROES = Set zero-inflated zeroes to 0.
parameter_help_hint_NANS_THRESHOLD = $(parameter_help_float)
parameter_help_description_NANS_THRESHOLD = Maximum undefined fraction.
parameter_help_hint_BIMODAL_THRESHOLD = $(parameter_help_float)
parameter_help_description_BIMODAL_THRESHOLD = Vote threshold for bimodal genes.
parameter_help_hint_ZEROINF_THRESHOLD = $(parameter_help_float)
parameter_help_description_ZEROINF_THRESHOLD = Zero-inflated vote threshold.
parameter_help_hint_UNIMODAL_THRESHOLD = $(parameter_help_float)
parameter_help_description_UNIMODAL_THRESHOLD = Unimodal vote threshold.
parameter_help_hint_BIN_DEA_ONLY_HVG = $(parameter_help_bool)
parameter_help_description_BIN_DEA_ONLY_HVG = Restrict DEA binarization to HVGs.
parameter_help_hint_BIN_LOGFC = $(parameter_help_float)
parameter_help_description_BIN_LOGFC = Minimum absolute log2 fold-change.
parameter_help_hint_BIN_CORRECTION = benjamini-hochberg | bonferroni
parameter_help_description_BIN_CORRECTION = P-value correction method.
parameter_help_hint_BIN_ALPHA = $(parameter_help_float)
parameter_help_description_BIN_ALPHA = Adjusted p-value threshold.
parameter_help_hint_BIN_METHOD = scboolseq | dea | consensus
parameter_help_description_BIN_METHOD = Method used to binarize macrostates.
parameter_help_hint_BINARIZATION_FILE = existing binarization csv
parameter_help_description_BINARIZATION_FILE = External binarization file.

parameter_help_hint_SPEC_FILE = existing yaml file
parameter_help_description_SPEC_FILE = Boolean inference specification file.
parameter_help_hint_INFERENCE_DIR = relative directory
parameter_help_description_INFERENCE_DIR = Inference output directory within project_dir.
parameter_help_hint_PRIOR_KNOWLEDGE = collectri | dorothea | file
parameter_help_description_PRIOR_KNOWLEDGE = Prior regulatory resource.
parameter_help_hint_GENEINFO_VERSION = bundled | latest | file
parameter_help_description_GENEINFO_VERSION = NCBI gene_info source.
parameter_help_hint_OMNIPATH_VERSION = latest | YYYY-MM-DD
parameter_help_description_OMNIPATH_VERSION = OmniPath resource version.
parameter_help_hint_HCOP_VERSION = bundled | latest | file
parameter_help_description_HCOP_VERSION = HCOP orthology version.
parameter_help_hint_DOROTHEA_API = modern | legacy
parameter_help_description_DOROTHEA_API = DoRothEA API source.
parameter_help_hint_DOROTHEA_COMPATIBILITY = $(parameter_help_bool)
parameter_help_description_DOROTHEA_COMPATIBILITY = Reproduce decoupler DoRothEA deduplication.
parameter_help_hint_DOROTHEA_LEVELS = A, B, C, D or any combination
parameter_help_description_DOROTHEA_LEVELS = DoRothEA confidence levels.
parameter_help_hint_MAX_CLAUSES = $(parameter_help_positive_integer)
parameter_help_description_MAX_CLAUSES = Maximum number of conjunctive terms joined by OR in each Boolean update function.
parameter_help_hint_BOUNDED_NONREACH = >= 1, optional
parameter_help_description_BOUNDED_NONREACH = Number of certificate iterations used for non-reachability constraints.
parameter_help_note_BOUNDED_NONREACH = Empty values use the complete default bound from BoNesis.
parameter_help_note2_BOUNDED_NONREACH = Configuration targets use the regulatory-domain size; observation targets use a tighter target-specific bound.
parameter_help_note3_BOUNDED_NONREACH = Final non-reachability constraints remain bounded to one iteration.
parameter_help_hint_CLAUSE_CONTINUATION_SOFT = $(parameter_help_bool)
parameter_help_hint_CLAUSE_CONTINUATION_RELAXED = $(parameter_help_bool)
parameter_help_hint_CLAUSE_CONTINUATION_SEED = $(parameter_help_bool)
parameter_help_hint_CLAUSE_CONTINUATION_LOCK = $(parameter_help_bool)
parameter_help_clause_continuation = Progressively increase clause bounds within one selection stage.
parameter_help_description_CLAUSE_CONTINUATION_SOFT = $(parameter_help_clause_continuation)
parameter_help_description_CLAUSE_CONTINUATION_RELAXED = $(parameter_help_clause_continuation)
parameter_help_description_CLAUSE_CONTINUATION_SEED = $(parameter_help_clause_continuation)
parameter_help_description_CLAUSE_CONTINUATION_LOCK = $(parameter_help_clause_continuation)
parameter_help_clause_continuation_note = Clause bounds are local to one stage; unchanged constraint levels can forward their structural witness.
parameter_help_note_CLAUSE_CONTINUATION_SOFT = $(parameter_help_clause_continuation_note)
parameter_help_note_CLAUSE_CONTINUATION_RELAXED = $(parameter_help_clause_continuation_note)
parameter_help_note_CLAUSE_CONTINUATION_SEED = $(parameter_help_clause_continuation_note)
parameter_help_note_CLAUSE_CONTINUATION_LOCK = $(parameter_help_clause_continuation_note)
parameter_help_hint_PATIENCE_CLAUSE_BOUND = duration
parameter_help_clause_bound_patience = Maximum time without a Clingo objective improvement before advancing an intermediate clause bound.
parameter_help_description_PATIENCE_CLAUSE_BOUND = $(parameter_help_clause_bound_patience)
parameter_help_clause_bound_patience_note = Use NUMBER[s|m|h|d]; 0 or an empty value disables patience.
parameter_help_clause_bound_patience_note2 = Ignored when clause continuation is disabled and at the target bound.
parameter_help_note_PATIENCE_CLAUSE_BOUND = $(parameter_help_clause_bound_patience_note)
parameter_help_note2_PATIENCE_CLAUSE_BOUND = $(parameter_help_clause_bound_patience_note2)
parameter_help_hint_DOMAIN_CONTINUATION_SOFT = $(parameter_help_bool)
parameter_help_hint_DOMAIN_CONTINUATION_RELAXED = $(parameter_help_bool)
parameter_help_hint_DOMAIN_CONTINUATION_SEED = $(parameter_help_bool)
parameter_help_hint_DOMAIN_CONTINUATION_LOCK = $(parameter_help_bool)
parameter_help_domain_continuation = Search candidate subdomains and expand a retained witness toward the complete domain.
parameter_help_description_DOMAIN_CONTINUATION_SOFT = $(parameter_help_domain_continuation)
parameter_help_description_DOMAIN_CONTINUATION_RELAXED = $(parameter_help_domain_continuation)
parameter_help_description_DOMAIN_CONTINUATION_SEED = $(parameter_help_domain_continuation)
parameter_help_description_DOMAIN_CONTINUATION_LOCK = Expand a seed-computed witness through candidate subdomains within the complete relaxed domain.
parameter_help_note_DOMAIN_CONTINUATION_LOCK = Lock keeps the seed solution when its witness was forwarded or is absent.
parameter_help_hint_PATIENCE_DOMAIN_WAVE = duration
parameter_help_domain_wave_patience = Full stagnation time after improving the best objective within one wave.
parameter_help_description_PATIENCE_DOMAIN_WAVE = $(parameter_help_domain_wave_patience)
parameter_help_domain_wave_patience_note = Use NUMBER[s|m|h|d]; 0 or an empty value disables wave patience.
parameter_help_domain_wave_patience_note2 = A new candidate reaching the same best objective guarantees up to 2m remain.
parameter_help_note_PATIENCE_DOMAIN_WAVE = $(parameter_help_domain_wave_patience_note)
parameter_help_note2_PATIENCE_DOMAIN_WAVE = $(parameter_help_domain_wave_patience_note2)
parameter_help_hint_MIN_DOMAIN_YIELD = >= 0, < 1
parameter_help_description_MIN_DOMAIN_YIELD = Minimum cumulative retained-node gain per node added during domain expansion.
parameter_help_note_MIN_DOMAIN_YIELD = Low-yield expansions are refreshed at constant size. Zero disables yield-based domain refreshes.
parameter_help_note2_MIN_DOMAIN_YIELD = Ignored when domain continuation is disabled.
parameter_help_hint_MAX_DOMAIN_REFRESHES = >= 0
parameter_help_description_MAX_DOMAIN_REFRESHES = Maximum number of constant-size domain refreshes before expansion resumes.
parameter_help_note_MAX_DOMAIN_REFRESHES = Zero disables domain refreshes.
parameter_help_note2_MAX_DOMAIN_REFRESHES = Ignored when domain continuation is disabled.
parameter_help_hint_MIN_SELF_LOOP_CONSTS = $(parameter_help_bool)
parameter_help_description_MIN_SELF_LOOP_CONSTS = Minimize one-node feedbacks.
parameter_help_hint_MIN_SELF_LOOP_INFER = $(parameter_help_bool)
parameter_help_description_MIN_SELF_LOOP_INFER = Minimize one-node feedbacks.
parameter_help_hint_CONFIG_FORMATS = csv, cfg, json or any combination
parameter_help_description_CONFIG_FORMATS = Configuration export formats.
parameter_help_hint_GRAPH_FORMATS = graphviz layouts
parameter_help_description_GRAPH_FORMATS = Graphviz layouts to export.
parameter_help_hint_INFER_LIMIT = >= 0, optional
parameter_help_description_INFER_LIMIT = Maximum number of inferred BNs.

parameter_help_hint_CLINGO_CONFIG_SOFT = $(parameter_help_clingo_configs)
parameter_help_hint_CLINGO_CONFIG_CONSTS = $(parameter_help_clingo_configs)
parameter_help_hint_CLINGO_CONFIG_RELAXED = $(parameter_help_clingo_configs)
parameter_help_hint_CLINGO_CONFIG_SEED = $(parameter_help_clingo_configs)
parameter_help_hint_CLINGO_CONFIG_LOCK = $(parameter_help_clingo_configs)
parameter_help_description_CLINGO_CONFIG_SOFT = Clingo configuration.
parameter_help_description_CLINGO_CONFIG_CONSTS = Clingo configuration.
parameter_help_description_CLINGO_CONFIG_RELAXED = Clingo configuration.
parameter_help_description_CLINGO_CONFIG_SEED = Clingo configuration.
parameter_help_description_CLINGO_CONFIG_LOCK = Clingo configuration.
parameter_help_note_CLINGO_CONFIG_SOFT = $(parameter_help_clingo_config_note)
parameter_help_note_CLINGO_CONFIG_CONSTS = $(parameter_help_clingo_config_note)
parameter_help_note_CLINGO_CONFIG_RELAXED = $(parameter_help_clingo_config_note)
parameter_help_note_CLINGO_CONFIG_SEED = $(parameter_help_clingo_config_note)
parameter_help_note_CLINGO_CONFIG_LOCK = $(parameter_help_clingo_config_note)

parameter_help_hint_CLINGO_MODE_SOFT = opt | optN | ignore
parameter_help_hint_CLINGO_MODE_CONSTS = opt | optN | ignore
parameter_help_hint_CLINGO_MODE_RELAXED = opt | optN | ignore
parameter_help_hint_CLINGO_MODE_SEED = opt | optN | ignore
parameter_help_hint_CLINGO_MODE_LOCK = opt | optN | ignore
parameter_help_hint_CLINGO_MODE_MIN = opt | optN | ignore
parameter_help_description_CLINGO_MODE_SOFT = Clingo mode used to handle optimization statements.
parameter_help_description_CLINGO_MODE_CONSTS = Clingo mode used to handle optimization statements.
parameter_help_description_CLINGO_MODE_RELAXED = Clingo mode used to handle optimization statements.
parameter_help_description_CLINGO_MODE_SEED = Clingo mode used to handle optimization statements.
parameter_help_description_CLINGO_MODE_LOCK = Clingo mode used to handle optimization statements.
parameter_help_description_CLINGO_MODE_MIN = Clingo mode used to handle optimization statements.
parameter_help_note_CLINGO_MODE_SOFT = $(parameter_help_clingo_mode_note)
parameter_help_note_CLINGO_MODE_CONSTS = $(parameter_help_clingo_mode_note)
parameter_help_note_CLINGO_MODE_RELAXED = $(parameter_help_clingo_mode_note)
parameter_help_note_CLINGO_MODE_SEED = $(parameter_help_clingo_mode_note)
parameter_help_note_CLINGO_MODE_LOCK = $(parameter_help_clingo_mode_note)
parameter_help_note_CLINGO_MODE_MIN = $(parameter_help_clingo_mode_note)
parameter_help_note2_CLINGO_MODE_SOFT = $(parameter_help_clingo_mode_note2)
parameter_help_note2_CLINGO_MODE_CONSTS = $(parameter_help_clingo_mode_note2)
parameter_help_note2_CLINGO_MODE_RELAXED = $(parameter_help_clingo_mode_note2)
parameter_help_note2_CLINGO_MODE_SEED = $(parameter_help_clingo_mode_note2)
parameter_help_note2_CLINGO_MODE_LOCK = $(parameter_help_clingo_mode_note2)
parameter_help_note2_CLINGO_MODE_MIN = $(parameter_help_clingo_mode_note2)
parameter_help_note3_CLINGO_MODE_SOFT = $(parameter_help_clingo_mode_note3)
parameter_help_note3_CLINGO_MODE_CONSTS = $(parameter_help_clingo_mode_note3)
parameter_help_note3_CLINGO_MODE_RELAXED = $(parameter_help_clingo_mode_note3)
parameter_help_note3_CLINGO_MODE_SEED = $(parameter_help_clingo_mode_note3)
parameter_help_note3_CLINGO_MODE_LOCK = $(parameter_help_clingo_mode_note3)
parameter_help_note3_CLINGO_MODE_MIN = $(parameter_help_clingo_mode_note3)

parameter_help_hint_CLINGO_STRATEGY_SOFT = bb,* | usc,*
parameter_help_hint_CLINGO_STRATEGY_CONSTS = bb,* | usc,*
parameter_help_hint_CLINGO_STRATEGY_RELAXED = bb,* | usc,*
parameter_help_hint_CLINGO_STRATEGY_SEED = bb,* | usc,*
parameter_help_hint_CLINGO_STRATEGY_LOCK = bb,* | usc,*
parameter_help_description_CLINGO_STRATEGY_SOFT = Clingo algorithm used to solve optimization statements.
parameter_help_description_CLINGO_STRATEGY_CONSTS = Clingo algorithm used to solve optimization statements.
parameter_help_description_CLINGO_STRATEGY_RELAXED = Clingo algorithm used to solve optimization statements.
parameter_help_description_CLINGO_STRATEGY_SEED = Clingo algorithm used to solve optimization statements.
parameter_help_description_CLINGO_STRATEGY_LOCK = Clingo algorithm used to solve optimization statements.
parameter_help_note_CLINGO_STRATEGY_SOFT = $(parameter_help_clingo_strategy_note)
parameter_help_note_CLINGO_STRATEGY_CONSTS = $(parameter_help_clingo_strategy_note)
parameter_help_note_CLINGO_STRATEGY_RELAXED = $(parameter_help_clingo_strategy_note)
parameter_help_note_CLINGO_STRATEGY_SEED = $(parameter_help_clingo_strategy_note)
parameter_help_note_CLINGO_STRATEGY_LOCK = $(parameter_help_clingo_strategy_note)
parameter_help_note2_CLINGO_STRATEGY_SOFT = $(parameter_help_clingo_strategy_note2)
parameter_help_note2_CLINGO_STRATEGY_CONSTS = $(parameter_help_clingo_strategy_note2)
parameter_help_note2_CLINGO_STRATEGY_RELAXED = $(parameter_help_clingo_strategy_note2)
parameter_help_note2_CLINGO_STRATEGY_SEED = $(parameter_help_clingo_strategy_note2)
parameter_help_note2_CLINGO_STRATEGY_LOCK = $(parameter_help_clingo_strategy_note2)

parameter_help_hint_CLINGO_THREADS = $(parameter_help_positive_integer)
parameter_help_description_CLINGO_THREADS = Number of threads used by the stage-level Clingo solver.
parameter_help_note_CLINGO_THREADS = Domain-continuation candidates always use one thread.

parameter_help_hint_TIMEOUT_SOFT = duration
parameter_help_hint_TIMEOUT_CONSTS = duration
parameter_help_hint_TIMEOUT_RELAXED = duration
parameter_help_hint_TIMEOUT_SEED = duration
parameter_help_hint_TIMEOUT_LOCK = duration
parameter_help_description_TIMEOUT_SOFT = Maximum total solver runtime.
parameter_help_description_TIMEOUT_CONSTS = Maximum total solver runtime.
parameter_help_description_TIMEOUT_RELAXED = Maximum total solver runtime.
parameter_help_description_TIMEOUT_SEED = Maximum total solver runtime.
parameter_help_description_TIMEOUT_LOCK = Maximum total solver runtime.
parameter_help_note_TIMEOUT_SOFT = $(parameter_help_timeout_note)
parameter_help_note_TIMEOUT_CONSTS = $(parameter_help_timeout_note)
parameter_help_note_TIMEOUT_RELAXED = $(parameter_help_timeout_note)
parameter_help_note_TIMEOUT_SEED = Required when max-nodes-seed is reached.
parameter_help_note_TIMEOUT_LOCK = $(parameter_help_timeout_note)

## END PARAMETER HELP ##
